language: c++
dist: xenial
sudo: false
os:
  - linux
compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - cmake-data
      - cmake




matrix:

  exclude:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc

  include:
      - os: linux
        compiler: gcc-7
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - graphviz
              - python3-dev
              - libgraphviz-dev
              - python3
              - python3-pip
              - python3-setuptools
              - g++-7
              - libboost1.58-all-dev
        env:
          - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && CTEST_OUTPUT_ON_FAILURE=1"
#     - os: linux
#       compiler: clang-6.0
#       addons:
#         apt:
#           sources:
#             - llvm-toolchain-xenial-6.0
#           packages:
#             - graphviz
#             - python3-dev
#             - libgraphviz-dev
#             - python3
#             - python3-pip
#             - python3-setuptools
#             - clang-6.0
#             - libboost1.58-all-dev
#       env:
#          - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0 && CTEST_OUTPUT_ON_FAILURE=1"

before_install:
    - pkg-config --libs-only-L libcgraph
    - pkg-config --cflags-only-I libcgraph
    - python3 -V
    - python -V
    - pip3 -V
    - pip -V
    - pip3 install --upgrade pip
    - eval "${MATRIX_EVAL}"

install:
  - pip3 install --user xmlrunner
  - pip3 install --user pygraphviz --install-option="--include-path=/usr/include/graphviz" --install-option="--library-path=/usr/lib/graphviz/"
  - pip3 install --user pygraphml

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: 
  - make VERBOSE=1
  - ctest -VV
  - make clang-tidy
  - cat clang-tidy.log

